### ISSUE TITLE
JOSS Review: No GitHub version listed

### ISSUE THREAD

**Issue by kbarnhart** [Geodels/bioLEC#1]
The version described in the [JOSS submission](https://github.com/openjournals/joss-reviews/issues/1530) is 1.0.0

There are presently no tags or releases listed on GitHub.

My assumption is that @tristan-salles is intentionally waiting to make changes indicated in review before tagging.

**Comment by tristan-salles** [comment]
Yes, you're right I am waiting for the end of the reviewing process...
