### ISSUE TITLE
JOSS Review: Links to API in RTFD

### ISSUE THREAD

**Issue by kbarnhart** [Geodels/bioLEC#8]
Another comment related to my [JOSS Review](https://github.com/openjournals/joss-reviews/issues/1530)... 

There are a number of places in the docs where I expected a link to the api documentation. For example the `landscapeConnectivity()` at the top of the [Quickstart](https://biolec.readthedocs.io/en/latest/usage.html#input). 

The package is overall really well linked, this sort of issue was the only one where I wanted links that weren't there. I find that this sort of link helps a lot when one is trying to teach themself from the documentation.

**Comment by tristan-salles** [comment]
I have added references to the API for the 3 main functions: 
+ `landscapeConnectivity()`
+ `computeLEC()`
+ `writeLEC()`

in the [Quick start guide](https://biolec.readthedocs.io/en/latest/usage.html) documentation.
