### ISSUE TITLE
JOSS Review: Statement of need in RTFD

### ISSUE THREAD

**Issue by kbarnhart** [Geodels/bioLEC#9]
@tristan-salles I thought that the statement of need was very clear in the the `paper.md` but not as clear on the RTFD page. 

[link to JOSS Review](https://github.com/openjournals/joss-reviews/issues/1530)

**Comment by tristan-salles** [comment]
The statement of need has been updated in the `readthedoc` [page](https://biolec.readthedocs.io/en/latest/) to reflect the `paper.md`section.
